
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed mainFixedContainer;

	private global::Gtk.Label testLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.Frame testFrame;

	private global::Gtk.Label drawingAreaLabel;

	private global::Gtk.ComboBox testComboBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainFixedContainer = new global::Gtk.Fixed ();
		this.mainFixedContainer.Name = "mainFixedContainer";
		this.mainFixedContainer.HasWindow = false;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.testLabel = new global::Gtk.Label ();
		this.testLabel.Name = "testLabel";
		this.testLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Suite");
		this.mainFixedContainer.Add (this.testLabel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.testLabel]));
		w1.X = 11;
		w1.Y = 31;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 600;
		this.GtkScrolledWindow.HeightRequest = 100;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.mainFixedContainer.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.GtkScrolledWindow]));
		w2.X = 9;
		w2.Y = 520;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.testFrame = new global::Gtk.Frame ();
		this.testFrame.WidthRequest = 600;
		this.testFrame.HeightRequest = 400;
		this.testFrame.Name = "testFrame";
		this.testFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		this.drawingAreaLabel = new global::Gtk.Label ();
		this.drawingAreaLabel.Name = "drawingAreaLabel";
		this.drawingAreaLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Drawing Area</b>");
		this.drawingAreaLabel.UseMarkup = true;
		this.testFrame.LabelWidget = this.drawingAreaLabel;
		this.mainFixedContainer.Add (this.testFrame);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.testFrame]));
		w3.X = 7;
		w3.Y = 75;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.testComboBox = global::Gtk.ComboBox.NewText ();
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("LineTo"));
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("BitBlt"));
		this.testComboBox.Name = "testComboBox";
		this.testComboBox.Active = 0;
		this.mainFixedContainer.Add (this.testComboBox);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.testComboBox]));
		w4.X = 70;
		w4.Y = 18;
		this.Add (this.mainFixedContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 632;
		this.DefaultHeight = 663;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.testComboBox.Changed += new global::System.EventHandler (this.OnTestComboBoxChanged);
	}
}
