
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed mainFixedContainer;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView dumpTextView;

	private global::Gtk.Frame testFrame;

	private global::Gtk.Label drawingAreaLabel;

	private global::Gtk.Label testLabel;

	private global::Gtk.ComboBox testComboBox;

	private global::Gtk.Button dumpButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainFixedContainer = new global::Gtk.Fixed ();
		this.mainFixedContainer.Name = "mainFixedContainer";
		this.mainFixedContainer.HasWindow = false;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.dumpTextView = new global::Gtk.TextView ();
		this.dumpTextView.WidthRequest = 600;
		this.dumpTextView.HeightRequest = 200;
		this.dumpTextView.CanFocus = true;
		this.dumpTextView.Name = "dumpTextView";
		this.dumpTextView.Editable = false;
		this.GtkScrolledWindow.Add (this.dumpTextView);
		this.mainFixedContainer.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.GtkScrolledWindow]));
		w2.X = 14;
		w2.Y = 286;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.testFrame = new global::Gtk.Frame ();
		this.testFrame.WidthRequest = 600;
		this.testFrame.HeightRequest = 200;
		this.testFrame.Name = "testFrame";
		this.testFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		this.drawingAreaLabel = new global::Gtk.Label ();
		this.drawingAreaLabel.Name = "drawingAreaLabel";
		this.drawingAreaLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Drawing Area</b>");
		this.drawingAreaLabel.UseMarkup = true;
		this.testFrame.LabelWidget = this.drawingAreaLabel;
		this.mainFixedContainer.Add (this.testFrame);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.testFrame]));
		w3.X = 21;
		w3.Y = 76;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.testLabel = new global::Gtk.Label ();
		this.testLabel.Name = "testLabel";
		this.testLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Suite");
		this.mainFixedContainer.Add (this.testLabel);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.testLabel]));
		w4.X = 24;
		w4.Y = 30;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.testComboBox = global::Gtk.ComboBox.NewText ();
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("BitBlt"));
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("LineTo"));
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("PolylineTo"));
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Ellipse"));
		this.testComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Polygon"));
		this.testComboBox.Name = "testComboBox";
		this.testComboBox.Active = 0;
		this.mainFixedContainer.Add (this.testComboBox);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.testComboBox]));
		w5.X = 79;
		w5.Y = 26;
		// Container child mainFixedContainer.Gtk.Fixed+FixedChild
		this.dumpButton = new global::Gtk.Button ();
		this.dumpButton.CanFocus = true;
		this.dumpButton.Name = "dumpButton";
		this.dumpButton.UseUnderline = true;
		this.dumpButton.Label = global::Mono.Unix.Catalog.GetString ("Dump");
		this.mainFixedContainer.Add (this.dumpButton);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.mainFixedContainer[this.dumpButton]));
		w6.X = 174;
		w6.Y = 23;
		this.Add (this.mainFixedContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 664;
		this.DefaultHeight = 562;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.testComboBox.Changed += new global::System.EventHandler (this.OnTestComboBoxChanged);
		this.dumpButton.Clicked += new global::System.EventHandler (this.OnDumpButtonClicked);
	}
}
